# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Pack
      run: dotnet pack --no-build --configuration Release
    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg --source "nuget.org" --configfile nuget.config
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
