# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.1
    - name: Build the project
      run: dotnet build ./Src --configuration Release --no-restore
      
    - name: Restore dependencies
      run: dotnet restore ./Src/RedisCache/RedisCache.csproj -s ${{ secrets.NUGET_URL }} --ignore-failed-sources 
    - name: Create directory
      run: mkdir nupkgs

    - name: Pack the project
      run: dotnet pack ./Src --configuration Release --no-build --output nupkgs -v n
      
    - name: Change directory
      run: cd nupkgs
      
    - name: Publish the package to NuGet.org
      run: dotnet nuget push *.nupkg -s ${{ secrets.NUGET_URL }} --api-key ${{ secrets.NUGET_API_KEY }}
